### ISSUE TITLE
Trying to Compile for MacStudio M1 - running into several issues.

### ISSUE THREAD

**Issue by zhordon** [unspok3n/beatportdl#40]
Hey, I've been trying to compile the latest version for the last couple of days on my M1 MacStudio using Sonoma.

I've been able to confirm that I have all of the dependencies installed:

`go version go1.23.4 darwin/arm64`

```
taglib-config --version
2.0.2
```
```
python3 -c "import zlib; print(zlib.ZLIB_VERSION)"
1.2.11
```
```
zig version
0.13.0
```

When opening Terminal and using the default makefile I get this message:

Default Code
```
darwin-arm64:
	@echo "Building for macOS ARM64"
	go clean -cache
	CGO_ENABLED=1 \
	GOOS=darwin \
	GOARCH=arm64 \
	CGO_LDFLAGS="-F${MACOS_SDK_PATH}/System/Library/Frameworks -L${MACOS_SDK_PATH}/usr/lib" \
	CC="${ZIG_CC} -target aarch64-macos ${MACOS_ARM64_LIB_PATH} -isysroot ${MACOS_SDK_PATH} -iwithsysroot /usr/include -iframeworkwithsysroot /System/Library/Frameworks" \
	CXX="${ZIG_CXX} -target aarch64-macos ${MACOS_ARM64_LIB_PATH} -isysroot ${MACOS_SDK_PATH} -iwithsysroot /usr/include -iframeworkwithsysroot /System/Library/Frameworks" \
	${BUILD_CMD} -o=${BUILD_DIR}/beatportdl-darwin-arm64 ${BUILD_SRC} 
```
Result
```
sudo make darwin-arm64 
Password:
Building for macOS ARM64
go clean -cache
CGO_ENABLED=1 \
	GOOS=darwin \
	GOARCH=arm64 \
	CGO_LDFLAGS="-F/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks -L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib" \
	CC="zig cc -target aarch64-macos  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -iwithsysroot /usr/include -iframeworkwithsysroot /System/Library/Frameworks" \
	CXX="zig c++ -target aarch64-macos  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -iwithsysroot /usr/include -iframeworkwithsysroot /System/Library/Frameworks" \
	go build -ldflags "-w -linkmode external -extldflags '-lstdc++'" -buildmode pie -o=./bin/beatportdl-darwin-arm64 ./cmd/beatportdl
# unspok3n/beatportdl/internal/taglib
internal/taglib/taglib.go:6:11: fatal error: 'tag_c.h' file not found
    6 |         #include <tag_c.h>
      |                  ^~~~~~~~~
1 error generated.
make: *** [darwin-arm64] Error 1
```
Now i've been able to get around the above error by adding the following to the makefile:

`CGO_CFLAGS="-I/usr/local/include/taglib" \`

Now this is the result I get:

```
sudo make darwin-arm64
Building for macOS ARM64
go clean -cache
CGO_ENABLED=1 \
	GOOS=darwin \
	GOARCH=arm64 \
	CGO_CFLAGS="-I/usr/local/include/taglib" \
	CGO_LDFLAGS="-F/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks -L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib" \
	CC="zig cc -target aarch64-macos  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -iwithsysroot /usr/include -iframeworkwithsysroot /System/Library/Frameworks" \
	CXX="zig c++ -target aarch64-macos  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -iwithsysroot /usr/include -iframeworkwithsysroot /System/Library/Frameworks" \
	go build -ldflags "-w -linkmode external -extldflags '-lstdc++'" -buildmode pie -o=./bin/beatportdl-darwin-arm64 ./cmd/beatportdl
# unspok3n/beatportdl/cmd/beatportdl
/usr/local/go/pkg/tool/darwin_arm64/link: running zig failed: exit status 1
/usr/local/zig/zig cc -target aarch64-macos -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -iwithsysroot /usr/include -iframeworkwithsysroot /System/Library/Frameworks -arch arm64 -Wl,-S -o $WORK/b001/exe/a.out /tmp/go-link-218119908/go.o /tmp/go-link-218119908/000000.o /tmp/go-link-218119908/000001.o /tmp/go-link-218119908/000002.o /tmp/go-link-218119908/000003.o /tmp/go-link-218119908/000004.o /tmp/go-link-218119908/000005.o /tmp/go-link-218119908/000006.o /tmp/go-link-218119908/000007.o /tmp/go-link-218119908/000008.o /tmp/go-link-218119908/000009.o /tmp/go-link-218119908/000010.o /tmp/go-link-218119908/000011.o /tmp/go-link-218119908/000012.o -F/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks -L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib -ltag -lz -ltag_c -lresolv -F/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks -L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib -framework CoreFoundation -framework CoreFoundation -framework Security -lstdc++
error: unable to find dynamic system library 'tag' using strategy 'paths_first'. searched paths:
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/libtag.tbd
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/libtag.dylib
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/libtag.so
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/libtag.a
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/libtag.tbd
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/libtag.dylib
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/libtag.so
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/libtag.a
error: unable to find dynamic system library 'tag_c' using strategy 'paths_first'. searched paths:
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/libtag_c.tbd
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/libtag_c.dylib
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/libtag_c.so
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/libtag_c.a
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/libtag_c.tbd
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/libtag_c.dylib
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/libtag_c.so
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/libtag_c.a

make: *** [darwin-arm64] Error 1
```
This is where I get stuck in the process. Any tips to move forward with a successful compile?

Thanks in Advance!

**Comment by zhordon** [comment]
Coding is not my expertise, but I have tried what you has suggested with the same result. 

Do I add the above to the Makefile, or is it something that strict has to be done in Terminal?

**Comment by unspok3n** [comment]
The example i provided is for terminal but if you really want you can set it in the makefile, just remove the double quotes before doing so, but i suggest using the `.env` file.

After running build command, do you see the flags you provided in the make output? Like this
```shell
CC="zig cc -target aarch64-macos -I/usr/local/include/taglib -L/usr/local/lib -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -iwithsysroot /usr/include -iframeworkwithsysroot /System/Library/Frameworks" \
CXX="zig c++ -target aarch64-macos -I/usr/local/include/taglib -L/usr/local/lib -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -iwithsysroot /usr/include -iframeworkwithsysroot /System/Library/Frameworks"
```

If yes, could you check that `libtag.a` and `libtag_c.a` files actually exist in the `/usr/local/lib` directory?

**Comment by zhordon** [comment]
Making the changes you suggested, this is what it spits out:

```
Building for macOS ARM64
go clean -cache
CGO_ENABLED=1 \
	GOOS=darwin \
	GOARCH=arm64 \
	CGO_CFLAGS="-I/usr/local/include/taglib" \
	CGO_LDFLAGS="-F/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks -L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib" \
	CC="zig cc -target aarch64-macos -I/usr/local/include/taglib -L/usr/local/lib -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -iwithsysroot /usr/include -iframeworkwithsysroot /System/Library/Frameworks" \
	CXX="zig c++ -target aarch64-macos -I/usr/local/include/taglib -L/usr/local/lib -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -iwithsysroot /usr/include -iframeworkwithsysroot /System/Library/Frameworks" \
	go build -ldflags "-w -linkmode external -extldflags '-lstdc++'" -buildmode pie -o=./bin/beatportdl-darwin-arm64 ./cmd/beatportdl
# unspok3n/beatportdl/cmd/beatportdl
/usr/local/go/pkg/tool/darwin_arm64/link: running zig failed: exit status 1
/usr/local/zig/zig cc -target aarch64-macos -I/usr/local/include/taglib -L/usr/local/lib -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -iwithsysroot /usr/include -iframeworkwithsysroot /System/Library/Frameworks -arch arm64 -Wl,-S -o $WORK/b001/exe/a.out /tmp/go-link-3182697824/go.o /tmp/go-link-3182697824/000000.o /tmp/go-link-3182697824/000001.o /tmp/go-link-3182697824/000002.o /tmp/go-link-3182697824/000003.o /tmp/go-link-3182697824/000004.o /tmp/go-link-3182697824/000005.o /tmp/go-link-3182697824/000006.o /tmp/go-link-3182697824/000007.o /tmp/go-link-3182697824/000008.o /tmp/go-link-3182697824/000009.o /tmp/go-link-3182697824/000010.o /tmp/go-link-3182697824/000011.o /tmp/go-link-3182697824/000012.o -F/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks -L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib -ltag -lz -ltag_c -lresolv -F/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks -L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib -framework CoreFoundation -framework CoreFoundation -framework Security -lstdc++
error: symbol _runtime.covctrs not attached to any (sub)section
    note: while parsing /tmp/go-link-3182697824/go.o

make: *** [darwin-arm64] Error 1
```
Any other suggestions?

**Comment by unspok3n** [comment]
I'm really sorry, my bad, i was actually running the dev build of zig where this bug was fixed. I will update the docs asap.
https://github.com/ziglang/zig/pull/21680

Grab the dev build from here https://ziglang.org/download/ and try running it again

**Comment by zhordon** [comment]
I'm still getting errors like this:

```
MACOS_ARM64_LIB_PATH="-L/usr/local/lib -I/usr/local/include/taglib" sudo make darwin-arm64
Building for macOS ARM64
go clean -cache
CGO_ENABLED=1 \
	GOOS=darwin \
	GOARCH=arm64 \
	CGO_LDFLAGS="-F/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks -L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib" \
	CC="zig cc -target aarch64-macos  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -iwithsysroot /usr/include -iframeworkwithsysroot /System/Library/Frameworks" \
	CXX="zig c++ -target aarch64-macos  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -iwithsysroot /usr/include -iframeworkwithsysroot /System/Library/Frameworks" \
	go build -ldflags "-w -linkmode external -extldflags '-lstdc++'" -buildmode pie -o=./bin/beatportdl-darwin-arm64 ./cmd/beatportdl
# runtime/cgo
error: unable to find zig installation directory '/usr/local/bin/zig': FileNotFound
make: *** [darwin-arm64] Error 1
```
The funny thing is that it is there.
![Screenshot 2024-12-12 at 10 03 39 PM](https://github.com/user-attachments/assets/33a04133-235e-4f4d-ae47-81294c6d3e08)

I'm currently in the process of removing it all, and then reinstalling and add it to PATH correctly. 

If you have any other suggestions let me know, otherwise I will continue to use the available release.

I will keep you posted.

**Comment by zhordon** [comment]
Through further research I've tried these 2 commands:

/usr/local/bin/zig cc --version  
/usr/local/bin/zig c++ --version

These were the results:

```
/usr/local/bin/zig cc --version  
clang version 19.1.0 (https://github.com/ziglang/zig-bootstrap 46b9e66db90230fe62404b27b85a378ccf2c82c2)
Target: aarch64-unknown-darwin23.6.0
Thread model: posix
InstalledDir: /usr/local/bin
```
```
/usr/local/bin/zig c++ --version
clang version 19.1.0 (https://github.com/ziglang/zig-bootstrap 46b9e66db90230fe62404b27b85a378ccf2c82c2)
Target: aarch64-unknown-darwin23.6.0
Thread model: posix
InstalledDir: /usr/local/bin
```

2 Things stand out to me about the above:

1. The Target happens to omit `macos` and instead says `unknown`
2. Zig refers to Clang 

I'm off to bed now, but if you have any other suggestions/directions I'm all ears, but likely will have to try again after work tomorrow.

**Comment by unspok3n** [comment]
Zig errors are sometimes misleading, i think it can't find the lib folder. Try moving the whole folder (with zig binary and /lib) somewhere else and then add it to PATH

**Comment by unspok3n** [comment]
Never really tested it with the clang, but you can specify `-mmacosx-version-min=14.3` in the CC and CXX variables to make the warnings disappear. And remove the duplicate `-ltag` and `-ltag_c`, they are already provided in the taglib.go

**Comment by zhordon** [comment]
I'm stubborn and determined but I seem to have found some success doing the following code changes in the makefile:

```
darwin-arm64:
	@echo "Building for macOS ARM64"
	go clean -cache
	CGO_ENABLED=1 \
	GOOS=darwin \
	GOARCH=arm64 \
	CGO_CFLAGS="-I/usr/local/include/taglib" \
	CGO_LDFLAGS="-F${MACOS_SDK_PATH}/System/Library/Frameworks -L${MACOS_SDK_PATH}/usr/lib" \
	CC="zig cc -target aarch64-macos -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -iwithsysroot /usr/include -iframeworkwithsysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -L/usr/local/lib" \
	CXX="zig c++ -target aarch64-macos -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -iwithsysroot /usr/include -iframeworkwithsysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -L/usr/local/lib" \
	${BUILD_CMD} -o=${BUILD_DIR}/beatportdl-darwin-arm64 ${BUILD_SRC}
```
Which resulted with this in Terminal:

```
sudo make darwin-arm64
Building for macOS ARM64
go clean -cache
CGO_ENABLED=1 \
	GOOS=darwin \
	GOARCH=arm64 \
	CGO_CFLAGS="-I/usr/local/include/taglib" \
	CGO_LDFLAGS="-F/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks -L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib" \
	CC="zig cc -target aarch64-macos -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -iwithsysroot /usr/include -iframeworkwithsysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -L/usr/local/lib" \
	CXX="zig c++ -target aarch64-macos -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -iwithsysroot /usr/include -iframeworkwithsysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -L/usr/local/lib" \
	go build -ldflags "-w -linkmode external -extldflags '-lstdc++'" -buildmode pie -o=./bin/beatportdl-darwin-arm64 ./cmd/beatportdl

```
![Screenshot 2024-12-12 at 11 29 25 PM](https://github.com/user-attachments/assets/9ef0a963-2f71-469e-98c2-abb6c7fa5ac1)

So it looks like a success, but I will do some testing with my build tomorrow.

I want to test out how the error log is supposed to work before closing the ticket.

Thanks you again for your patience and help!

**Comment by zhordon** [comment]
So in an update and follow up: 

Using the above setup I was able to get it to build on commit [3814934](https://github.com/unspok3n/beatportdl/commit/3814934d37fe6f7ff34c0e4f539da32048034d49) 

I'm trying to test out the error logging file feature that was implemented from #25 but I'm not seeing a file being created in the directory. Am I missing something in my config file for that?

Now when I try build your latest commit - [b4babef ](https://github.com/unspok3n/beatportdl/commit/b4babef6e0f4876101b013293e8b35ba1e2db1f4) using the above settings for make file I get a new error message:

```
sudo make darwin-arm64
Building for macOS ARM64
go clean -cache
CGO_ENABLED=1 \
	GOOS=darwin \
	GOARCH=arm64 \
	CGO_CFLAGS="-I/usr/local/include/taglib" \
	CGO_LDFLAGS="-F/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks -L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib" \
	CC="zig cc -target aarch64-macos -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -iwithsysroot /usr/include -iframeworkwithsysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -L/usr/local/lib" \
	CXX="zig c++ -target aarch64-macos -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -iwithsysroot /usr/include -iframeworkwithsysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -L/usr/local/lib" \
	go build -ldflags "-w -linkmode external -extldflags '-lstdc++'" -buildmode pie -o=./bin/beatportdl-darwin-arm64 ./cmd/beatportdl
# unspok3n/beatportdl/cmd/beatportdl
cmd/beatportdl/downloader.go:135:25: undefined: GetStreamSegments
cmd/beatportdl/downloader.go:139:28: app.downloadSegments undefined (type *application has no field or method downloadSegments)
cmd/beatportdl/downloader.go:144:13: undefined: RemuxToM4A
make: *** [darwin-arm64] Error 1
```
By the looks of it, it would appear I'm missing nothing that was recently added. Any suggestions on what I should do?

**Comment by unspok3n** [comment]
You have to enable `write_error_log` in the config

**Comment by unspok3n** [comment]
Regarding error, my bad, i moved needledrop.go from internal/beatport to cmd/beatportdl and it wasn't added to git for some reason, try again on the latest commit

**Comment by zhordon** [comment]
Thank you again for everything!

I have it all working out now on the latest build.

`write_error_log: true` and copying over my previous makefile over allows me to build without issues.

```
darwin-arm64:
	@echo "Building for macOS ARM64"
	go clean -cache
	CGO_ENABLED=1 \
	GOOS=darwin \
	GOARCH=arm64 \
	CGO_CFLAGS="-I/usr/local/include/taglib" \
	CGO_LDFLAGS="-F${MACOS_SDK_PATH}/System/Library/Frameworks -L${MACOS_SDK_PATH}/usr/lib" \
	CC="zig cc -target aarch64-macos -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -iwithsysroot /usr/include -iframeworkwithsysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -L/usr/local/lib" \
	CXX="zig c++ -target aarch64-macos -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -iwithsysroot /usr/include -iframeworkwithsysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -L/usr/local/lib" \
	${BUILD_CMD} -o=${BUILD_DIR}/beatportdl-darwin-arm64 ${BUILD_SRC}
```

That is what works on my setup. Now to try and get this all going on my Windows PC lol.
