### ISSUE TITLE
tag track: invalid file

### ISSUE THREAD

**Issue by bascurtiz** [unspok3n/beatportdl#41]
https://www.beatport.com/track/ca-va-piquer-feat-charly-king/13110489
`Finished downloading Ça va piquer (feat. Charly King) (Radio Edit Instrumental) [FLAC]
tag track: invalid file`

https://www.beatport.com/track/neo-tokyo-konrad-celinski-remix/9672530
`Finished downloading Neo-Tokyo (Konrad Celiński Remix) (Instrumental) [FLAC]
tag track: invalid file`

https://www.beatport.com/track/tanzt/4242606
`Finished downloading Tanzt! (R.F.N. Pop Wave Video Instrumental Extended Edit) [FLAC]
tag track: invalid file`

https://www.beatport.com/track/yo-soy/10176361
`Finished downloading Yo Soy (Instrumental Version) [FLAC]
tag track: invalid file`

I believe it has something to do with the ê, ô, é, etc. chars in artist/title or anywhere basically.
Happens when using built-in search function, aswell as manually targetting these urls, aswell as thru a txt-file.

Can you fix this?

Next to that, can you push a new release?
I'm having trouble compiling the latest code on Windows myself.

**Comment by bascurtiz** [comment]
Confirmed:
When I set it to `track_file_template: "{id} - {isrc}"` in `beatportdl-config.yml` , no such error.

This indicates that the more exotic characters, atleast on Windows, are the culprit to `tag track: invalid file`:
Since by default it tries to write `artist` and `title` to the filename, that need to be sanitized prior.

**Comment by cheesetosti** [comment]
Fixed in the latest git code. For now you can either build a binary from source code or wait for a new [release](https://github.com/unspok3n/beatportdl/releases).

@unspok3n, don't you think it's time for version 1.0.5 now? A lot has been changed and fixed :D

**Comment by unspok3n** [comment]
Not fixed, it's windows specific, i'm afraid it can't be fixed without directly modifying taglib https://github.com/taglib/taglib/issues/1048

I'll see what i can do anyway

**Comment by unspok3n** [comment]
Should be fixed, tested with wine on mac, the error no longer appears for the mentioned tracks
766e87fdc7aeda29941172ac17e3da8b96555f35
